Repository badgeteam/website, pull requests merged in 2024-04, with the labels that each got.

#112 Hh2024 dev
  content/en/docs/Badges/Hackerhotel 2024/software-development/HH2024_ESPhome.jpeg
  content/en/docs/Badges/Hackerhotel 2024/software-development/Modify Standard Firmware/_index.md
  content/en/docs/Badges/Hackerhotel 2024/software-development/_index.md
Labels: documentation

#113 Move CD to Hugo 0.124.1
  .github/workflows/cd.yml
  .travis.yml
Labels: documentation, enhancement

#115 Update actions/checkout for CD
  .github/workflows/cd.yml
Labels: bug
